#cloud-config

users:
	-	name: ubuntu
		sudo: ALL=(ALL) NOPASSWD:ALL
		groups: users, admin
		home: /home/ubuntu
		shell: /bin/bash

ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
	- apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
runcmd:
  - sudo systemctl enable apache2
  - sudo systemctl restart apache2
  - sudo systemctl status apache2 >> /home/ubuntu/apache_logs.log
write_files:
  - path: /var/www/html/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <body>

      <h1>Hello world!</h1>
      <p>This is a text.</p>

      </body>
      </html>

  - path: /var/www/html/info.php
    content: |
      <?php

      // M346: Zeige alle Informationen, defaults to INFO_ALL
      phpinfo();

      ?>

  - path: /var/www/html/db.php
    content: |
      <?php
      //M346 database
      $servername = "127.0.0.1";
      $username = "admin";
      $password = "password";
      $dbname = "mysql";

      // Create connection
      $conn = new mysqli($servername, $username, $password, $dbname);
      // Check connection
      if ($conn->connect_error) {
              die("Connection failed: " . $conn->connect_error);
      }

      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
              echo($row["Host"] . " / " . $row["User"] . "<br />");
      }
      //var_dump($result);
      ?>
