#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh-authorized-keys:
      - |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCGqtx0Oo7cFZavwtzOgd32J2O9CrKWrVbEznmFfG4zQ4rJGxb1JCGNMwT9EryDezz7Mh0fKuAEHC2GIzpGr3Z1FbLB0lOWNDbWvBEp9w39lG5oTMdLjpw2ZtHIGSeoD0mxbwjsp7yXX6LerIaMs3HahTUJn9Xx/boSFEg8xgdctfwYiHaNaZxDLH9b/rivcn/De3vEM+qo+souBMxx1IOpSzQhbXAc0BueiTJ3XL4CWqOrJQQUpyLapGtPW+LSuo0mHyYGZn+Ny0JeThLXREoEHDdegy0Qw9RiaiIoJgBGZ31Y1MBOxTfgdE9iRNpdGVHsYAg3f+KPnQt2mxkxrcOz geschäft-pc

ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
  - mariadb-server
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service
